### ISSUE TITLE
Add module Graphene Screenshot

### ISSUE THREAD

**Issue by aslakknutsen** [arquillian/arquillian-universe-bom#13]
Figure out if there is an easy way we could auto enable it if Graphene and Recorder Screenshot is enabled.. Possible needs to be built into the Graphene integration it self.

ref https://github.com/arquillian/arquillian-graphene/tree/master/extension/screenshooter

**Comment by lordofthejars** [comment]
I have talked with Stefan about this. We need to integrate this project http://www.randelshofer.ch/monte/ I talked with the owner and since we maintain his authoring, we can use without any problem.

**Comment by lordofthejars** [comment]
The problem is that this project is not in github nor maven central, so we need to upload data and release to Maven central.

**Comment by aslakknutsen** [comment]
Hmm, sure you're not referring to this: https://github.com/arquillian/arquillian-universe-bom/issues/9 ?

**Comment by lordofthejars** [comment]
Well the idea is to add this library to video recorder so, video recorder doesn't not depend on external program but a java library.

**Comment by aslakknutsen** [comment]
Right, but it's a Recorder issue, not Graphene :)

**Comment by lordofthejars** [comment]
yes
