### ISSUE TITLE
Remove temp exclude of JUnit from Recorder when 1.1.0.Alpha2 of Recorder is out

### ISSUE THREAD

**Issue by aslakknutsen** [arquillian/arquillian-universe-bom#15]

**Comment by smiklosovic** [comment]
can be released asap but i dont know how far is @lordofthejars with the new recorder which is more licence friendly

**Comment by lordofthejars** [comment]
I would release as is, I need to release the video recorder first, and this
will take some time.
El dg, 27 set 2015 a les 9:20 Štefan Miklošovič notifications@github.com
va escriure:

**Comment by aslakknutsen** [comment]
Ok, I can push a new release.
