### ISSUE TITLE
Remove temp exclude of JUnit/Hamcrest from Governor/Jira when 1.0.0.Alpha3 of Governor is out 

### ISSUE THREAD

**Issue by aslakknutsen** [arquillian/arquillian-universe-bom#17]

**Comment by smiklosovic** [comment]
repaired and can be released, i do not have the rights to do it on my own anymore, I think the github governor by @lordofthejars will take a lot of time so there is not need to wait as alpha releases are cheap

**Comment by lordofthejars** [comment]
Hi Stefan in fact github integration is done, it only needs some
refactorings and send the PR. Let me try to do it today or tomorrow.
El dg, 27 set 2015 a les 9:18 Štefan Miklošovič notifications@github.com
va escriure:

**Comment by aslakknutsen** [comment]
I can do the release when time comes.

**Comment by lordofthejars** [comment]
Great, release this version, and when we have github integrated then let's release again. @smiklosovic any planning for releasing the first final version? Any features you would like to introduce?

**Comment by smiklosovic** [comment]
lets say having github integrated you can cut first final

**Comment by smiklosovic** [comment]
@aslakknutsen @lordofthejars github integration was added (https://github.com/arquillian/arquillian-governor/commit/f1dfd4260b6918f0f0a9dfb88cd6f6d783a30d4a), you can proceed to the first final release

**Comment by aslakknutsen** [comment]
@smiklosovic cool! 1.0.0.Final it is! :) I'll release/announce tomorrow.. :+1:
