### ISSUE TITLE
Re export recorder video-impl with new version of Recorder

### ISSUE THREAD

**Issue by aslakknutsen** [arquillian/arquillian-universe-bom#28]
ref: https://issues.jboss.org/browse/ARQ-1989

wait: 1.1.0.Alpha5

**Comment by smiklosovic** [comment]
repaired here https://github.com/arquillian/arquillian-recorder/commit/83453f00b3a2c332a1e43d3fb0dcef3421917159

@MatousJobanek would be nice to double check this

**Comment by MatousJobanek** [comment]
@smiklosovic Looks good. Good job :+1:

**Comment by aslakknutsen** [comment]
Cool, anyone have any other issues to add.. Or should I just cut a new release?

**Comment by smiklosovic** [comment]
@lordofthejars would you do that jenkins stuff please?

**Comment by lordofthejars** [comment]
@smiklosovic now I am in devoxx mode, I will try it to do it.

**Comment by smiklosovic** [comment]
@aslakknutsen @MatousJobanek please release 1.1.0.Final of recorder

**Comment by aslakknutsen** [comment]
@smiklosovic  1.1.0.Final released
