### ISSUE TITLE
shrinkwrap 1.2.3 -> 1.2.6, selenium 1.53.0 -> 1.53.1 shrinkwrap-descriptors not explicitly set

### ISSUE THREAD

**Issue by andyglick** [arquillian/arquillian-universe-bom#57]
have submitted pull request #56

this change effects the versions of 

shrinkwrap, which has a GA release @ 1.2.6
selenium which has a GA release of @ 1.53.1
shrinkwrap-descriptors pushed from the default @ 2.0.0-alpha-8 via transitive dependencies to explicit setting @ 2.0.0-alpha-10

have tested this configuration with weld embedded, glassfish managed and jboss eap 6.4.0 managed and remote

**Comment by bartoszmajsak** [comment]
Resolved @3cc3a761e02f2c122c82dda8a4928699021bfd39
