### ISSUE TITLE
Update Selenium Version in Universe to match Drone

### ISSUE THREAD

**Issue by codylerum** [arquillian/arquillian-universe-bom#85]
Universe was recently updated to 1.1.13.6 which updated Drone to 2.4.1. Drone 2.4.1 has Selenium 3.5.1 but the universe bom still has 3.4.0.

This causes issues with Guava 23.0 as selenium 3.4.0 is using a method that was removed in Guava 23

**Comment by bartoszmajsak** [comment]
`1.1.13.7` is in central. Thanks for reporting!

**Comment by codylerum** [comment]
@bartoszmajsak Works perfect. Thanks!
